site_name: Appunti Laboratorio Reti di calcolatori - Emiddio Ingenito
site_author: Emiddio Ingenito
site_description: Appunti completi del corso di Laboratorio di Reti di calcolatori, Università degli Studi di Milano. Apparati di rete, Cablaggi, DHCP, Subnetting, Routing, OSPF, RIP, VLAN, NAT, ACL e configurazioni Cisco.
copyright: 'Emiddio Ingenito - Emikodes</a>'
site_url: https://emikodes-UniMI.github.io/retilab/
repo_url: https://github.com/emikodes-UniMI/retilab/
repo_name: emikodes-UniMI/retilab
edit_uri: edit/main/docs/

# Configurazione Tema Material
theme:
  name: material
  language: it
  logo: branding/logo.png
  favicon: branding/favicon.ico

  features:
    - navigation.expand         # Apre le categorie cliccando sulla freccia
    - navigation.top            # Bottone "Torna su" che appare scrollando
    - navigation.tracking       # Evidenzia la sezione corrente mentre leggi
    - toc.integrate             # Indice dei contenuti integrato nella sidebar sinistra
    - search.suggest            # Suggerimenti mentre scrivi nella ricerca
    - search.highlight          # Evidenzia le parole trovate
    - search.share              # Pulsante per condividere la ricerca
    - content.code.copy         # Pulsante per copiare i blocchi di codice
    - content.action.edit       # Pulsante "Modifica questa pagina" su GitHub

  palette:
    # 1. Configurazione DARK (Total Black/Grey)
    - scheme: slate
      primary: black   # Header bianco (il testo diventa nero in automatico)
      accent: red     # Consiglio: mantieni un accent minimo per i link (es. lime, yellow o white), 
      toggle:
        icon: material/weather-night
        name: Passa alla modalità chiara

    - scheme: default
      primary: white   # Header bianco (il testo diventa nero in automatico)
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità scura

  # Tipografia professionale
  font:
    text: Roboto
    code: Roboto Mono

# Plugin aggiuntivi
plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#2f3ab2" # Colore dello sfondo dell'immagine (blu indaco)
        color: "#ffffff"            # Colore del testo
# Estensioni Markdown (Per rendere gli appunti belli e funzionali)
markdown_extensions:
  # Permette di usare le note colorate (!!! note "Nota Bene")
  - admonition
  
  # Permette di usare icone (es: :smile:)
  - attr_list
  
  # Liste di definizione
  - def_list
  
  # Note a piè di pagina
  - footnotes
  
  # Supporto avanzato per tabelle
  - tables
  
  # Crea link automatici alle sezioni (l'icona # che appare a lato titoli)
  - toc:
      permalink: true
  
  # Gestione avanzata del codice (Syntax Highlighting)
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences    # Permette di annidare blocchi di codice
  
  # Tabbed code blocks (Utile per mostrare es. Config Cisco vs Linux)
  - pymdownx.tabbed:
      alternate_style: true 
  
  # Checkbox nelle liste [x]
  - pymdownx.tasklist:
      custom_checkbox: true

  # Supporto Formule Matematiche (LaTeX) - Fondamentale per i tuoi appunti $G=(V,E)$
  - pymdownx.arithmatex:
      generic: true
      
extra:
  generator: false
